# Generated by Django 4.2.6 on 2023-10-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptons',
            new_name='description',
        ),
    ]
